CREATE TABLE [Patient].[Appointment] (
    [Id]                    INT              IDENTITY (1, 1) NOT NULL,
    [Guid]                  UNIQUEIDENTIFIER CONSTRAINT [DF__Appointmen__Guid__70DDC3D8] DEFAULT (newid()) NOT NULL,
    [PatientId]             INT              NOT NULL,
    [DoctorId]              INT              NOT NULL,
    [CoordinatorId]         INT              NULL,
    [BranchId]              INT              NULL,
    [AppointmentDate]       DATETIME         NULL,
    [SlotStartTime]         TIME (7)         NULL,
    [SlotEndTime]           TIME (7)         NULL,
    [AppointmentName]       VARCHAR (MAX)    NULL,
    [Description]           VARCHAR (200)    NULL,
    [IsPatientAttended]     BIT              CONSTRAINT [DF_Appointment_IsPatientAttended] DEFAULT ((0)) NULL,
    [IsDoctorAttended]      BIT              CONSTRAINT [DF_Appointment_IsDoctorAttended] DEFAULT ((0)) NULL,
    [IsCoordinatorAttended] BIT              CONSTRAINT [DF_Appointment_IsCoordinatorAttended] DEFAULT ((0)) NULL,
    [VideoUrl]              VARCHAR (MAX)    NULL,
    [AppointmentDuration]   INT              NULL,
    [IsDoctorSelected]      BIT              CONSTRAINT [DF_Appointment_IsDoctorSelected] DEFAULT ((1)) NULL,
    [IsRescheduled]         BIT              CONSTRAINT [DF_Appointment_IsRescheduled] DEFAULT ((0)) NULL,
    [IsConfirmed]           BIT              CONSTRAINT [DF_Appointment_IsConfirmed] DEFAULT ((0)) NULL,
    [NextReviewDate]        DATETIME         NULL,
    [ReviewDoctorId]        INT              NULL,
    [PreviousAppointmentId] INT              NULL,
    [IsDeleted]             BIT              CONSTRAINT [DF__Appointme__IsDel__71D1E811] DEFAULT ((0)) NULL,
    [CreatedDt]             DATETIME         CONSTRAINT [DF__Appointme__Creat__72C60C4A] DEFAULT (getdate()) NULL,
    [CreatedBy]             VARCHAR (50)     CONSTRAINT [DF__Appointme__Creat__73BA3083] DEFAULT (suser_sname()) NULL,
    [CreatedById]           INT              NULL,
    [ModifiedDt]            DATETIME         NULL,
    [ModifiedBy]            VARCHAR (50)     NULL,
    [ModifiedById]          INT              NULL,
    [CreatedByName]         VARCHAR (255)    CONSTRAINT [DF__Appointme__Creat__5AF96FB1] DEFAULT (suser_sname()) NULL,
    [ModifiedName]          VARCHAR (255)    CONSTRAINT [DF__Appointme__Modif__5BED93EA] DEFAULT (suser_sname()) NULL,
    CONSTRAINT [PK__Appointm__3214EC07071B0E08] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ__Appointm__A2B5777DE6F32055] UNIQUE NONCLUSTERED ([Guid] ASC)
);
GO

