CREATE TABLE [Patient].[Patient] (
    [Id]                      INT              IDENTITY (1, 1) NOT NULL,
    [Guid]                    UNIQUEIDENTIFIER CONSTRAINT [DF__Patient__Guid__66603565] DEFAULT (newid()) NULL,
    [UserId]                  INT              NULL,
    [Title]                   VARCHAR (200)    NULL,
    [FirstName]               VARCHAR (200)    NULL,
    [MiddleName]              VARCHAR (200)    NULL,
    [LastName]                VARCHAR (200)    NULL,
    [CountryCode]             NVARCHAR (10)    NULL,
    [MobileNumber]            VARCHAR (50)     NULL,
    [AlternativeMobileNumber] VARCHAR (50)     NULL,
    [Email]                   NVARCHAR (256)   NULL,
    [Gender]                  VARCHAR (200)    NULL,
    [DateOfBirth]             DATETIME         NULL,
    [AddressProofType]        VARCHAR (200)    NULL,
    [AddressProofTypeId]      INT              NULL,
    [IdentificationNumber]    VARCHAR (200)    NULL,
    [MaritalStatus]           VARCHAR (200)    NULL,
    [OccupationName]          VARCHAR (200)    NULL,
    [OccupationId]            INT              NULL,
    [ReligionId]              INT              NULL,
    [ReligionName]            VARCHAR (200)    NULL,
    [IncomeGroupName]         VARCHAR (200)    NULL,
    [IncomeGroupId]           INT              NULL,
    [EducationName]           VARCHAR (200)    NULL,
    [EducationId]             INT              NULL,
    [BloodGroup]              VARCHAR (200)    NULL,
    [RelationshipType]        VARCHAR (200)    NULL,
    [RelationshipTypeId]      INT              NULL,
    [RelationName]            VARCHAR (200)    NULL,
    [MothersMaidenName]       VARCHAR (200)    NULL,
    [CityName]                VARCHAR (200)    NULL,
    [CityId]                  INT              NULL,
    [StateName]               VARCHAR (200)    NULL,
    [StateId]                 INT              NULL,
    [Address1]                VARCHAR (200)    NULL,
    [Address2]                VARCHAR (200)    NULL,
    [PatientPhotoURL]         VARCHAR (200)    NULL,
    [RelationId]              INT              NULL,
    [CreatedByUserId]         INT              NULL,
    [BranchName]              VARCHAR (200)    NULL,
    [IsDeleted]               BIT              CONSTRAINT [DF__Patient__IsDelet__6754599E] DEFAULT ((0)) NULL,
    [CreatedDt]               DATETIME         CONSTRAINT [DF__Patient__Created__68487DD7] DEFAULT (getdate()) NULL,
    [CreatedBy]               VARCHAR (50)     CONSTRAINT [DF__Patient__Created__693CA210] DEFAULT (suser_sname()) NULL,
    [ModifiedDt]              DATETIME         NULL,
    [ModifiedBy]              VARCHAR (50)     NULL,
    [CreatedByName]           VARCHAR (255)    CONSTRAINT [DF__Patient__Created__0307610B] DEFAULT (suser_sname()) NULL,
    [ModifiedName]            VARCHAR (255)    CONSTRAINT [DF__Patient__Modifie__03FB8544] DEFAULT (suser_sname()) NULL,
    CONSTRAINT [PK__Patient__3214EC076866BBA7] PRIMARY KEY CLUSTERED ([Id] ASC),
    CONSTRAINT [UQ__Patient__A2B5777D9F7C1854] UNIQUE NONCLUSTERED ([Guid] ASC)
);
GO

