CREATE TABLE [dbo].[Users] (
    [UserId]               INT                IDENTITY (1, 1) NOT NULL,
    [UserGuid]             UNIQUEIDENTIFIER   CONSTRAINT [DF_Users_UserGuid] DEFAULT (newid()) NOT NULL,
    [AccessFailedCount]    INT                CONSTRAINT [DF_Users_AccessFailedCount] DEFAULT ((0)) NOT NULL,
    [ConcurrencyStamp]     NVARCHAR (MAX)     NULL,
    [Email]                NVARCHAR (256)     NULL,
    [SecondaryEmail]       NVARCHAR (256)     NULL,
    [EmailConfirmed]       BIT                CONSTRAINT [DF_Users_EmailConfirmed] DEFAULT ((0)) NOT NULL,
    [FirstName]            NVARCHAR (MAX)     NULL,
    [LastName]             NVARCHAR (MAX)     NULL,
    [LockoutEnabled]       BIT                CONSTRAINT [DF_Users_LockoutEnabled] DEFAULT ((1)) NOT NULL,
    [LockoutEnd]           DATETIMEOFFSET (7) NULL,
    [NormalizedEmail]      NVARCHAR (256)     NULL,
    [NormalizedUserName]   NVARCHAR (256)     NULL,
    [PasswordHash]         NVARCHAR (MAX)     NULL,
    [PasswordEnabled]      BIT                CONSTRAINT [DF_Users_PasswordEnabled] DEFAULT ((0)) NOT NULL,
    [CountryCode]          NVARCHAR (10)      NULL,
    [PhoneNumber]          NVARCHAR (MAX)     NULL,
    [PhoneNumberConfirmed] BIT                CONSTRAINT [DF_Users_PhoneNumberConfirmed] DEFAULT ((0)) NOT NULL,
    [SecondaryPhoneNumber] NVARCHAR (20)      NULL,
    [Registered]           BIT                CONSTRAINT [DF_Users_ProfileConfirmed] DEFAULT ((0)) NOT NULL,
    [SecurityStamp]        NVARCHAR (MAX)     NULL,
    [TwoFactorEnabled]     BIT                CONSTRAINT [DF_Users_TwoFactorEnabled] DEFAULT ((0)) NOT NULL,
    [LoginTypeId]          INT                CONSTRAINT [DF_Users_LoginTypeId] DEFAULT ((1)) NOT NULL,
    [UserName]             NVARCHAR (256)     NULL,
    [UserTypeId]           INT                CONSTRAINT [DF_Users_UserTypeId] DEFAULT ((1)) NOT NULL,
    [City]                 NVARCHAR (256)     NULL,
    [State]                NVARCHAR (256)     NULL,
    [Country]              NVARCHAR (256)     NULL,
    [PinCode]              NVARCHAR (10)      NULL,
    [ImgUrl]               NVARCHAR (MAX)     NULL,
    [ForgotPasswordOtp]    NVARCHAR (50)      NULL,
    [Otp]                  NVARCHAR (10)      NULL,
    [OtpSentDt]            DATETIME           CONSTRAINT [DF_Users_OtpSentDt] DEFAULT (getdate()) NULL,
    [IsAcceptedTandC]      BIT                CONSTRAINT [DF_Users_IsAcceptedTandC] DEFAULT ((0)) NOT NULL,
    [IsDeleted]            BIT                CONSTRAINT [DF_Users_IsDeleted] DEFAULT ((0)) NOT NULL,
    [CreatedBy]            NVARCHAR (MAX)     CONSTRAINT [DF_Users_CreatedBy] DEFAULT (suser_sname()) NULL,
    [CreatedDt]            DATETIME2 (7)      CONSTRAINT [DF_Users_CreatedDt] DEFAULT (getdate()) NULL,
    [UpdatedBy]            NVARCHAR (MAX)     CONSTRAINT [DF_Users_UpdatedBy] DEFAULT (suser_sname()) NULL,
    [UpdatedDt]            DATETIME2 (7)      CONSTRAINT [DF_Users_UpdatedDt] DEFAULT (getdate()) NULL,
    [CreatedByName]        VARCHAR (255)      DEFAULT (suser_sname()) NULL,
    [ModifiedName]         VARCHAR (255)      DEFAULT (suser_sname()) NULL,
    CONSTRAINT [PK_Users] PRIMARY KEY CLUSTERED ([UserId] ASC)
);

